version: '3.8'

services:
  web:
    build: .
    container_name: coffee_shop_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=coffee_shop
    networks:
      - coffee_network

  mongodb:
    image: mongo:7.0
    container_name: coffee_shop_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - coffee_network

volumes:
  mongodb_data:

networks:
  coffee_network:
    driver: bridge
